### ISSUE TITLE
The content transform returning error

### ISSUE THREAD

**Issue by viterzbayraku** [versoly/taos#1]
This code returning error `SyntaxError: Unexpected token ':'`

```
module.exports = {
  content: {
    transform: (content) => content.replace(/taos:/g, ''),
  },
}
```

**Comment by volkandkaya** [comment]
Try using some of

```js
module.exports = {
  content: {
    files: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    transform: (content) => content.replace(/taos:/g, ''),
  },
  theme: {
    extend: {},
  },
  plugins: [require('taos/plugin')],
  safelist: [
    '!duration-0',
    '!delay-0',
    'html.js :where([class*="taos:"]:not(.taos-init))',
  ],
};
```

Might require files.

**Comment by viterzbayraku** [comment]
> Try using some of
> 
> ```js
> module.exports = {
>   content: {
>     files: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
>     transform: (content) => content.replace(/taos:/g, ''),
>   },
>   theme: {
>     extend: {},
>   },
>   plugins: [require('taos/plugin')],
>   safelist: [
>     '!duration-0',
>     '!delay-0',
>     'html.js :where([class*="taos:"]:not(.taos-init))',
>   ],
> };
> ```
> 
> Might require files.

![Знімок екрана 2022-10-02 о 23 11 20](https://user-images.githubusercontent.com/4019353/193474218-9a6b1ab1-0867-4c68-aa31-e3a0018c8636.png)
