### ISSUE TITLE
Does not work well with a flex

### ISSUE THREAD

**Issue by CoCoSol007** [versoly/taos#13]
Hey, for my personal website, I created a flex with my projects cards.
![Screenshot 2024-04-27 175402](https://github.com/versoly/taos/assets/96190446/9b208bfd-1830-4511-963a-d3d1daf976ea)
The code :
```html
<div class="container mx-auto my-8 flex flex-wrap justify-center">
       <div class="flex flex-row m-5 w-full lg:w-1/3 px-4 mb-4 duration-300 hover:scale-105 bg-gray-900 p-6 rounded-lg shadow-md border border-gray-700">
...
```
I want to apply an animation to each card, but it didn't work.
![Screenshot 2024-04-27 175527](https://github.com/versoly/taos/assets/96190446/75b80c8b-dd80-4210-ac6b-ba995977e79b)
The code :
```html
<div class="container mx-auto my-8 flex flex-wrap justify-center">
    <div class="duration-[600ms] delay-100 taos:[transform:translate3d(0,200px,0)_scale(0.6)] taos:opacity-0" data-taos-offset="100">
         <div class="flex flex-row m-5 w-full lg:w-1/3 px-4 mb-4 duration-300 hover:scale-105 bg-gray-900 p-6 rounded-lg shadow-md border border-gray-700">
...
```

**Comment by CoCoSol007** [comment]
PS: it's a Svelte project

**Comment by volkandkaya** [comment]
You shouldn't need to create a wrapper div. Can just add it to flex

**Comment by CoCoSol007** [comment]
Yes, it's work. Thx
