### ISSUE TITLE
Animation restarts on window resize

### ISSUE THREAD

**Issue by megaarmos** [versoly/taos#15]
### **Steps to Reproduce:**
1. Open the webpage [https://versoly.com/taos](https://versoly.com/taos).
2. Start resizing the browser window.

### **Expected Behavior:**
The webpage should resize without any animations restarting.

### **Actual Behavior:**
Animations on the webpage restart when the browser window is resized.

**Comment by kuvallini** [comment]
Do you have any solution for this? The problem still exists.

**Comment by megaarmos** [comment]
This issue was closed. I think this was intended behaviour.
