### ISSUE TITLE
Resizing?

### ISSUE THREAD

**Issue by cmalpeli** [versoly/taos#3]
Great library!  I noticed that resizing the browser on desktop causes the previously animated content to disappear.  It doesn't seem to re-animate consistently either after resize.  Is this s known issue?  You can replicate it on the demo site.

**Comment by volkandkaya** [comment]
Confirmed the issue, i will need to add a check after to readd elements in view.

**Comment by cmalpeli** [comment]
Hi @volkandkaya did you happen to have a chance to look into this issue?

**Comment by RyanRoberts** [comment]
It would be good to get a fix for this :)

**Comment by volkandkaya** [comment]
Fixed, please give it a try.

**Comment by volkandkaya** [comment]
I didn't think about mobile height changes, so I removed some code that might have fixed that (reduce bundle size).

I will test tomorrow on a Safari device.

**Comment by RyanRoberts** [comment]
Cool, thanks. I'm not great with JS so I don't have my own suggestions to make but with the help of a certain AI I did come up with this temporary solution that may help, or not. https://gist.github.com/RyanRoberts/6260530cf100c37a1f3bb3795dcbd1a3/revisions?diff=split

Thanks for looking into it.

**Comment by volkandkaya** [comment]
When resizing it needs to rerun initElement to get offsets and set the trigger for each element. I had some performance and other issues. This seemed to be the best solution.

**Comment by volkandkaya** [comment]
Updated can you try 1.0.5 @RyanRoberts

**Comment by RyanRoberts** [comment]
That's working great! Thanks for the update.

**Comment by cmalpeli** [comment]
Thanks @volkandkaya - I think this may still be an issue on desktop resize.  Was this fix just for mobile?

**Comment by volkandkaya** [comment]
What issue are you having on desktop resizing?

**Comment by volkandkaya** [comment]
What issue are you having on desktop resizing @cmalpeli ?

**Comment by cmalpeli** [comment]
@volkandkaya on desktop, if I resize, the previously animated content disappears and then re-animates on the next scroll event.

**Comment by cmalpeli** [comment]
@volkandkaya if you see here on the example site, all the animated content disappears and then re-animates on scroll when you resize the window:

https://versoly.com/taos#fade
