### ISSUE TITLE
Animations not triggering if component or element is already on viewport.

### ISSUE THREAD

**Issue by emeraldBD** [versoly/taos#6]
I am using TAOS with Angular v15.
I have successfully installed it, however the animations on the above the fold content is not triggering.
But the lower content animations are fine.
Is there a way to fix this?

**Comment by volkandkaya** [comment]
At the moment we don't support JS frameworks, it may work with some (doesn't with React it seems).

Most likely an issue with JS loading after the HTML.

Look at 

```<script>document.documentElement.classList.add('js')</script>```
